const menu = [
  {
    id: 1,
    title: 'Aloo parantha',
    category: 'breakfast',
    price: 70.0,
    img: './images/alooparatha.webp',
    desc: `Enjoy our soft and hot aloo paratha just like you enjoy at home. No compromises at all.`,
  },
  {
    id: 2,
    title: 'Veg thali',
    category: 'lunch',
    price: 120.0,
    img: './images/veg thali.webp',
    desc: `Introducing our all-in-one veg cuisine for you. Delicious and spicy. Try it now. `,
  },
  {
    id: 3,
    title: 'Mango Juice',
    category: 'Drinks',
    price: 50.0,
    img: './images/mango juice.jpg',
    desc: `Made with the best of the best mangoes to bless your taste buds. Hurry up order right now.`,
  },
  {
    id: 4,
    title: 'Dosa',
    category: 'breakfast',
    price: 70.0,
    img: './images/dosa.jpg',
    desc: `We understand your love for south indian dishes and want you to enjoy our dosa. Made only for you.`,
  },
  {
    id: 5,
    title: 'Paneer tikka',
    category: 'lunch',
    price: 150.0,
    img: './images/paneer tikka.jpg',
    desc: `For the paneer lovers out there, dont miss out on our special paneer tikka. We promise you are gonna love it.`,
  },
  {
    id: 6,
    title: 'Lassi',
    category: 'Drinks',
    price: 50.0,
    img: './images/lassi.webp',
    desc: 'Your saviour in the summer. Enjoy the cool lassi with added badam and kesar',
  },
  {
    id: 7,
    title: 'Sandwich',
    category: 'breakfast',
    price: 40.0,
    img: './images/sandwich.webp',
    desc: `For the ones who like to have it light and tasty. Try it now to experience the light and yummy sandwich`,
  },
  {
    id: 8,
    title: 'Chicken naan',
    category: 'lunch',
    price: 150.0,
    img: './images/easy-butter-chicken-naan.jpg',
    desc: `For the non veg lovers, we have chicken with naan for you. Enjoy the tender chicken with hot and soft naan. order right now`,
  },
  {
    id: 9,
    title: 'Coke',
    category: 'Drinks',
    price: 30.0,
    img: './images/coke.jpg',
    desc: `The legendary coke will go along with any of the items and will be a perfect combo.`,
  },
]
export default menu
